- name: Crear directorio de la app
  ansible.builtin.file:
    path: /opt/infra-web
    state: directory
    owner: admin
    group: docker
    mode: '0755'

- name: Copiar compose al servidor
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/infra-web/docker-compose.yml
    mode: '0644'

- name: Crear archivo .env para Docker Compose
  ansible.builtin.copy:
    dest: /opt/infra-web/.env
    content: "AWS_ACCOUNT_ID={{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    mode: '0600'

- name: Asegurar que el CLI de AWS esté instalado para el handshake
  ansible.builtin.apt:
    name: awscli
    state: present
    update_cache: yes
  become: true

- name: Autenticar el Docker local de la EC2 con AWS ECR
  ansible.builtin.shell: |
    aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin {{ lookup('env', 'AWS_ACCOUNT_ID') }}.dkr.ecr.us-east-2.amazonaws.com
  changed_when: false

- name: Desplegar contenedores (Traefik SSL Automático)
  community.docker.docker_compose_v2:
    project_src: /opt/infra-web
    state: present
    pull: always