---
- name: Instalar dependencias previas de Docker (GPG)
  ansible.builtin.apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg]
    state: present
    update_cache: yes

- name: Crear directorio keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar clave GPG oficial de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Obtener arquitectura dpkg
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Agregar repositorio Docker
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    architectures: [arm64]
    uris: [https://download.docker.com/linux/debian]
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    signed_by: /etc/apt/keyrings/docker.asc
    state: present

- name: Instalar Docker y Compose
  ansible.builtin.apt:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    state: present

- name: Iniciar servicio Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Agregar admin al grupo docker
  ansible.builtin.user:
    name: admin
    groups: docker
    append: yes