---
- name: Hardening y Configuración Inicial del Nodo AWS 
  hosts: aws_production 
  become: yes 
  
  tasks: 
    
    - name: Actualizar la lista de paquetes del sistema operativo (apt update)
      ansible.builtin.apt: 
        update_cache: yes 
        cache_valid_time: 3600 

    - name: Asegurar que utilidades básicas estén instaladas
      ansible.builtin.apt:
        name: 
          - htop
          - curl
          - git
        state: present 