services:
  # =========================================
  # TRAEFIK (El Proxy Dinámico)
  # =========================================
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false" 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" 
      
      - "--entrypoints.web.address=:80"        
      - "--entrypoints.websecure.address=:443" 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # =========================================
  # BACKEND (La API)
  # =========================================
  backend-portfolio:
    image: ghcr.io/ezequieldlv/ez-backend:latest
    container_name: backend-portfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true" 
      
      - "traefik.http.routers.backend.rule=Host(`api.ez-lab.site`)"
      - "traefik.http.routers.backend.entrypoints=web" 
      
      - "traefik.http.services.backend.loadbalancer.server.port=8585"

  # =========================================
  # FRONTEND (La Web Visible)
  # =========================================
  frontend-portfolio:
    image: ghcr.io/ezequieldlv/ez-frontend:latest
    container_name: frontend-portfolio
    restart: unless-stopped
    depends_on:
      - backend-portfolio 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ez-lab.site`) || Host(`www.ez-lab.site`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"